import type { Metadata } from "next";
import GFonts from "next/font/google";
import "@/styles/globals.css";
import theme from "@/configs/theme.json";
import type { FontLoader } from "@/types/fonts";
import type { CssVariable } from "next/dist/compiled/@next/font";

const FontPrimary = (GFonts as Record<string, FontLoader<CssVariable>>)[
  theme.typography.fontFamily.primary
];
const FontSecondary = (GFonts as Record<string, FontLoader<CssVariable>>)[
  theme.typography.fontFamily.secondary
];

const primaryFont = FontPrimary({
  variable: "--font-primary",
  subsets: ["latin"],
});

const secondaryFont = FontSecondary({
  variable: "--font-secondary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${primaryFont.variable} ${secondaryFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
